### PR TITLE
CMR-5107: Bounds to IndexRanges

### PR DESCRIPTION
**Pull request by oubiwann**
The proposed update to UMM-Var 1.2 has been made; this PR represents the changes we needed to make in order to support the update.

This update will remove a great deal of confusion that has already arisen around the metadata being saved in the given fields, and should make things much easier for future developers/project contributors.

### CODE REVIEW

**Comment by oubiwann** [comment]
Looking into a failing build ...

**Comment by oubiwann** [comment]
Build should be fixed now; I've emailed Simon C. with a request to change the schema (the issue was that a required field that should be an array had min items set to 0; setting it to 2 did the trick).

**Comment by oubiwann** [comment]
Note that there are no changes for tests due to the fact that the code that tests this autogenerates tests based upon the schemas. As an example, the failing build was due to an issue with the schema; when that was fixed (and the changes pushed back to the Metadata Quality team), the tests passed.

**Comment by mschmele** [comment]
> We got lucky that there is no additional migration needed for this change.

I thought I was going crazy when I looked at that, haha. Makes for a nice and easy review

**Pull request merged**
