### PR TITLE
CMR-4722

### PR DESCRIPTION
**Pull request by ygliuvt**
Bounding box constraint matching granules outside of bounding box.

### CODE REVIEW

**Comment by mschmele** [comment]
The theory behind this is pretty interesting and a standard practice in GIS calculations, especially where floating-point arithmetic is used (according to what bit of googling I've done). In essence, you're approximating an upper-bound for margin of error in floating-point operations. If two points are less than or equal to epsilon distance from each other, they're considered equal. It's not going to be 0, but it'll be close

If we want to generate machine epsilon to be super fancy and precise: https://en.wikipedia.org/wiki/Machine_epsilon#How_to_determine_machine_epsilon

**Comment by ygliuvt** [comment]
I have fixed two issues:

1/ Coordinate at the equator are not handled correctly in math computation.

2/ Spatial bounding box search with points latitude at exactly the orbit start latitude is not handled correctly.

See attached google earth visualization. You can see the erroneous matches around the equator are eliminated with the fix.
after_fix_matches_at_the_orbit
after_fix_erroneous_matches_around_equator_are_eliminated

**Comment by chris-durbin** [comment]
I'm not entirely sure how the Ruby code is packaged, but I assume we'll need to update the source Ruby repo as well, and potentially add some tests in there.

**Comment by ygliuvt** [comment]
> I'm not entirely sure how the Ruby code is packaged, but I assume we'll need to update the source Ruby repo as well, and potentially add some tests in there.
All the code is in CMR. I don't know if we need to maintain the old Ruby project as well.

**Pull request merged**
