### PR TITLE
Cmr 8032

### PR DESCRIPTION
**Pull request by TylerHeald1**

### CODE REVIEW

**Review by jaybarra — APPROVED** [review]

**Comment by ygliuvt** [comment]
Can you put a link to the wiki on how to build the Oracle ci docker image here?

**Comment by TylerHeald1** [comment]
Put up some simple instructions on the wiki on building the Oracle 19c docker image. It should be all that needs to be done assuming that the code on this branch is being used.
https://wiki.earthdata.nasa.gov/display/CMR/Docker+Oracle+19c+Container

**Review by ygliuvt — APPROVED** [review]

**Comment by ygliuvt** [comment]
Can you put some documentation on how the Oracle docker image is used in CI in the wiki page?

**Comment by TylerHeald1** [comment]
Added a description of how the image is used on CI

**Pull request merged**
