### PR TITLE
CMR-5388: Add cmr-exchange projects

### PR DESCRIPTION
**Pull request by oubiwann**
image

This  pulls in CMR exchange projects into the `cmr-exchange` subdir.

Note that for this PR, you won't want to use rebase, but rather simply "merge".

### CODE REVIEW

**Comment by chris-durbin** [comment]
I think site-templates and message-queue-lib already exist in the CMR today. Did you make sure to omit those from the cmr-exchange subdir? Are there any other projects you know of that live in both locations?

**Comment by oubiwann** [comment]
Yeah, I didn't include the message-queue-lib for the reason you mentioned; I'll have to check on the site-templates in CMR ... things might have diverged.

**Comment by oubiwann** [comment]
Only differences in site-templates were README and project.clj, so I will remove the one brought in from cmr-exchange.

**Comment by oubiwann** [comment]
Updated and ready for merge ...

**Comment by oubiwann** [comment]
Just added a PR image ... seemed appropriate ;-)

**Comment by chris-durbin** [comment]
So once we merge this in we'll have to update Bamboo and Travis CI to use the new location for the sub repos. We should keep versioning the individual libraries and apps the way we have been and publishing to clojars. Is there anything else that should change in our workflow as a result of moving all these projects into this single repo?

**Comment by oubiwann** [comment]
Yeah, Bamboo for service-bridge should be the only thing that needs to be updated; everything else keeps operating as-is.

**Comment by oubiwann** [comment]
Finished green a minute after your post :-)

**Pull request merged**
